import { Lora, Raleway, Space_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const space = Space_Mono({
  weight: "400",
  variable: "--font-space",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="mytheme" lang="en" className="scroll-smooth">
      <body
        className={`${lora.variable} ${raleway.variable} ${space.variable} antialiased`}
      >
        {children}
        
        {/* Toast Notifications */}
        <Toaster
          position="top-right"
          reverseOrder={true}
          toastOptions={{
            duration: 4000,
            style: {
              fontFamily: 'var(--font-lora)',
            },
          }}
        />
        
        {/* ShipNotes.dev Widget */}
        <script
          src="https://shipnotes.dev/widget.js"
          data-shipnotes-project="shipnotes"
          data-position="bottom-right"
          data-theme="light"
          data-show-count="true"
          data-days="30"
          async
        ></script>
      </body>
    </html>
  );
}
